### ISSUE TITLE
Portable in all platform

### ISSUE THREAD

**Issue by binarymaker** [slightlynybbled/libmathq15#21]
I need to use fixed-point operation across multiple projects

I have checked your code with mplab xc16 compiler against your assembly code. I feel both are approximate same

```
; -- Assembly code

_q15_mul:
    ; w3:w2 = w1 * w0
    mul.ss  w0, w1, w2
    
    ; w0 = (w3:w2) >> 15
    rlc	    w2, w2
    rlc	    w3, w3
    
    ; w0 = w3
    mov	    w3, w0
    
    return
```

```
!  C disassembly code optimization lvl 1

!q15_t q15_mul(q15_t multiplicand, q15_t multiplier){
0x4F0: MOV W1, W2
!    int32_t product = ((int32_t)multiplicand * (int32_t)multiplier) >> 15;
0x4F2: MUL.SS W0, W2, W2
0x4F4: SL W3, #1, W4
0x4F6: LSR W2, #15, W0
0x4F8: IOR W4, W0, W0
!    return (q15_t)product;
!}
0x4FA: RETURN
```
Can I use portable c code across or should I use handwritten assembly code

Thanks for your awesome work.

**Comment by slightlynybbled** [comment]
Agreed.  For multiplication, the C-generated code appears to be very similar in execution time as well as functionality.

Glad to be of service.  I haven't mucked with this library in years, but I still use it!  Glad that you are able to use it as well.  If you make any improvements, feel free to open a pull request.

**Comment by binarymaker** [comment]
I desired that go with c code. Any way compiler gives guaranty for logic otherwise porting with multiple projects is very hard in my case

below addition code also almost the same in execution speed with a small modification
```
! Addition function C disassembly code optimization lvl 1 

!q15_t q15_add(q15_t addend, q15_t adder){
!    int16_t result = addend + adder;
0x472: ADD W1, W0, W2
!    
!    if(addend > 0 && adder > 0 && result < 0)
0x474: CP0 W0
0x476: BRA LE, .L3
0x478: CP0 W1
0x47A: BRA LE, .L3
0x47C: CP0 W2
0x47E: BRA LT, .L5
!    {
!      result = 32767;
0x48E: MOV #0x7FFF, W2
0x490: BRA .L4
!    }
!    else if (addend < 0 && adder < 0 && result > 0)
0x480: CP0 W0
0x482: BRA GE, .L4
0x484: CP0 W1
0x486: BRA GE, .L4
0x488: CP0 W2
0x48A: BRA LE, .L4
0x48C: BRA .L7
!    {
!      result  = -32768;
0x492: MOV #0x8000, W2
!    }
!     
!    return (q15_t)result;
!}
0x494: MOV W2, W0
0x496: RETURN

```

I am new to the fixed point, please refer me good reference material. your blog was amazing.
Thanks

**Comment by slightlynybbled** [comment]
The [fixed point math](http://forembed.com/how-fixed-point-math-works.html) entry lays out the basics.  Fixed point really starts to shine when working with real-world sensors b/c fixed point will saturate.  This makes a big difference when used in PID loops and other real-world phenomenon b/c it emulates how the real world works with no modification.
